Repository 10up/block-components, pull requests merged in 2022-05, with the labels that each got.

#7 Add: `Image`, `MediaToolbar` Components and `useMedia` hook
  .github/workflows/e2e-tests.yml
  README.md
  components/image/index.js
  components/image/readme.md
  components/index.js
  components/media-toolbar/index.js
  components/media-toolbar/readme.md
  cypress/integration/IconPicker.spec.js
  cypress/integration/Image.spec.js
  cypress/support/commands.js
  example/.wp-env.json
  example/images/1920-1080.png
  example/package.json
  example/src/blocks/image-example/block.json
  example/src/blocks/image-example/edit.js
  example/src/blocks/image-example/index.js
  example/src/index.js
  hooks/index.js
  hooks/use-media/index.js
Labels: New Component

#66 Add: `Link` Component
  components/index.js
  components/link/index.js
  components/link/readme.md
  cypress/integration/Link.spec.js
  cypress/support/commands.js
  cypress/support/index.js
  example/plugin.php
  example/src/blocks/link-example/block.json
  example/src/blocks/link-example/edit.js
  example/src/blocks/link-example/index.js
  example/src/index.js
  hooks/use-on-click-outside.js
  package-lock.json
  package.json
Labels: [Type] Enhancement, New Component

#114 Fix: add documentation to undocumented components and hooks
  api/register-icons/readme.md
  components/icon-picker/readme.md
  hooks/use-filtered-list/readme.md
  hooks/use-has-selected-inner-block/index.js
  hooks/use-has-selected-inner-block/readme.md
  hooks/use-icons/readme.md
  hooks/use-media/readme.md
  hooks/use-request-data/readme.md
Labels: [Type] Documentation, [Type] Enhancement
