Repository 10up/block-components, pull requests merged in 2022-12, with the labels that each got.

#179 Fix failing e2e tests
  .github/workflows/e2e-tests.yml
  components/link/index.js
  cypress.config.js
  cypress.json
  cypress/e2e/IconPicker.spec.js
  cypress/e2e/Image.spec.js
  cypress/e2e/Link.spec.js
  cypress/e2e/Repeater.spec.js
  cypress/e2e/registerBlockExtension.spec.js
  cypress/support/e2e.js
  example/plugin.php
  package-lock.json
  package.json
Labels: [Type] Enhancement

#158 Move `Counter` to a separate component
  components/counter/index.js
  components/index.js
  components/rich-text-character-limit/index.js
Labels: [Type] Enhancement

#113 Add: `useScript` hook
  README.md
  hooks/index.js
  hooks/use-script/index.js
  hooks/use-script/readme.md
Labels: New Component

#184 fix pass fallback value to focal point picker if value is undefined
  components/image/index.js
  components/image/readme.md
Labels: [Type] Bug, [Component] Image
