Repository 10up/block-components, pull requests merged in 2022-07, with the labels that each got.

#127 add support for passing multiple blocks to the registerBlockExtension API
  api/register-block-extension/index.js
  api/register-block-extension/readme.md
Labels: [Type] Enhancement

#132 add `useBlockParentAttributes` hook
  README.md
  hooks/index.js
  hooks/use-block-parent-attributes/index.js
  hooks/use-block-parent-attributes/readme.md
Labels: [Type] Enhancement, New Hook

#133 add `RichTextCharacterLimit` component
  components/index.js
  components/rich-text-character-limit/index.js
  components/rich-text-character-limit/readme.md
  example/src/blocks/rich-text-character-limit/index.js
Labels: [Type] Enhancement, New Component

#135 fix styling of icons inside icon picker
  components/icon-picker/icon-picker.js
Labels: [Type] Bug

#136 fix use max width and height instead of forced 100%
  components/icon-picker/icon-picker.js
Labels: [Type] Enhancement
