Repository 10up/block-components, pull requests merged in 2022-02, with the labels that each got.

#85 Fix: custom class names are not being respected by the register block extension api
  README.md
  api/registerBlockExtension.js
  example/src/extensions/background-pattern/edit.js
  example/src/extensions/background-pattern/index.js
  example/src/index.js
  index.js
Labels: [Type] Bug

#88 Fix: clean up edge cases in icon picker related components
  components/IconPicker/icon-picker.js
  components/IconPicker/icon.js
  components/IconPicker/inline-icon-picker.js
  example/src/blocks/icon-picker-example/edit.js
  hooks/use-filtered-list.js
  hooks/use-icons.js
  icons/store/reducer.js
  icons/store/selectors.js
Labels: [Type] Bug, [Component] Icon Picker

#90 add github action that auto deploys @next version of npm package
  .github/workflows/release-next-npm-version.yml
Labels: [Type] Enhancement

#89 Add testing to block components
  .eslintignore
  .github/workflows/e2e-tests.yml
  .github/workflows/linting.yml
  .github/workflows/unit-tests.yml
  .gitignore
  README.md
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/IconPicker.spec.js
  cypress/integration/registerBlockExtension.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  example/package-lock.json
  example/src/blocks/icon-picker-example/block.json
  icons/store/__snapshots__/reducer.test.js.snap
  icons/store/reducer.test.js
  icons/store/selectors.test.js
  package-lock.json
  package.json
Labels: [Type] Enhancement

#93 Switch package to ship a transpiled version
  .github/workflows/e2e-tests.yml
  .github/workflows/release-next-npm-version.yml
  .gitignore
  components/ContentPicker/PickedItem.js
  components/ContentSearch/SearchItem.js
  components/ContentSearch/index.js
  components/CustomBlockAppender/index.js
  components/is-admin.js
  example/package-lock.json
  example/package.json
  hooks/use-has-selected-inner-block.js
  hooks/use-icons.js
  hooks/use-request-data.js
  icons/store/selectors.js
  package-lock.json
  package.json
  webpack.config.js
Labels: [Type] Enhancement

#73 Fix: Link Component Popover state
  components/Link/index.js
  example/src/blocks/link-example/block.json
  example/src/blocks/link-example/edit.js
  example/src/blocks/link-example/index.js
  example/src/index.js
  hooks/use-on-click-outside.js
  index.js
Labels: [Type] Enhancement

#83 Feature: Add ColorSetting Component
  README.md
  components/ColorSetting/index.js
  index.js
Labels: New Component
