Repository 10up/block-components, pull requests merged in 2024-05, with the labels that each got.

#318 Maintenance: Update Dependencies
  .github/workflows/compressed-size.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/linting.yml
  .github/workflows/release-next-npm-version.yml
  .github/workflows/release-npm-version.yml
  .github/workflows/release-testing-npm-version.yml
  .github/workflows/unit-tests.yml
  .nvmrc
  cypress/e2e/Repeater.spec.js
  example/package.json
  example/plugin.php
  package-lock.json
  package.json
  stores/icons/__snapshots__/reducer.test.js.snap
Labels: [Type] Infrastructure, [Type] Code Quality

#320 Migrate `ColorSetting` component to TS
  components/color-settings/index.js
  components/color-settings/index.tsx
  example/src/blocks/color-settings-example/block.json
  example/src/blocks/color-settings-example/edit.js
  example/src/blocks/color-settings-example/index.js
Labels: [Type] Code Quality

#322 Migrate `Counter` component to TS
  components/counter/index.tsx
  components/counter/readme.md
  components/styled-components-context/index.tsx
  example/src/blocks/counter-example/block.json
  example/src/blocks/counter-example/edit.js
  example/src/blocks/counter-example/index.js
Labels: [Type] Code Quality

#324 Fix: use unknown instead of any for unknown additional props
  components/author/index.tsx
  components/post-author/index.tsx
  components/post-date/index.tsx
  components/post-meta/index.tsx
  hooks/use-block-parent-attributes/index.ts
Labels: [Type] Code Quality

#321 Feature: IconPicker TypeScript Conversion
  components/icon-picker/icon-picker-toolbar-button.tsx
  components/icon-picker/icon-picker.tsx
  components/icon-picker/icon.tsx
  components/icon-picker/index.tsx
  components/icon-picker/inline-icon-picker.tsx
  example/src/blocks/icon-picker-example/edit.tsx
  package-lock.json
  package.json
Labels: [Component] Icon Picker, [Type] Code Quality
